name: example-actions
on:
  push:
    branches: ["main"]

jobs:
  build-test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Setup python environment
        run: |
          python3 -m venv venv
          source venv/bin/activate

      - name: Install libraries
        run: |
          pip install fastapi uvicorn sqlalchemy databases httpx pytest

      - name: Tests
        run: |
          pytest test_main.py